## Update Profile
POST   http://localhost:9090/update_profile_data
Content-Type: application/json

{
    "token":"593771c19016f1e76a0bd2bc4751f4547ae3c6a6b3fb068e891a4956ffabd944",
    "bio":"Hey I am Subrat ",
"email":"subratsethi501@gmail.com",
"password":"password"
}

# GET http://localhost:9090/get_user_and_profile
# Content-Type: application/json

# {
#   "token": "eb2fdd41631675cd8aad10ebe86c6b77e2f7bb7be57e6f803178b03f224cc78a"

# }
