## Update Profile
POST   http://localhost:9090/update_profile_data
Content-Type: application/json

{
    "token":"5bad788db690e8484dafdf9696ae4d2be5742a023e497fa0b934813304fcc62a",
    "bio":"Hey I am Subrat ",
"email":"subratsethi501@gmail.com",
"password":"password"
}

# GET http://localhost:9090/get_user_and_profile
# Content-Type: application/json

# {
#   "token": "eb2fdd41631675cd8aad10ebe86c6b77e2f7bb7be57e6f803178b03f224cc78a"

# }
